import React from "react";
import {Inter} from 'next/font/google'

import './globals.css'

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Radio',
    description: 'Generated by Me',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={`min-h-screen flex flex-col justify-between ${inter.className}`}>{children}</body>
        </html>
    )
}
